import koreanIcon from '@/assets/icons/foodCategory/korean.svg'
import japaneseIcon from '@/assets/icons/foodCategory/japanese.svg'
import chineseIcon from '@/assets/icons/foodCategory/chinese.svg'
import westernIcon from '@/assets/icons/foodCategory/western.svg'
import asianIcon from '@/assets/icons/foodCategory/asian.svg'
import fastfoodIcon from '@/assets/icons/foodCategory/fastfood.svg'
import chickenIcon from '@/assets/icons/foodCategory/chicken.svg'
import bunsikIcon from '@/assets/icons/foodCategory/bunsik.svg'
import dietIcon from '@/assets/icons/foodCategory/diet.svg'

interface MAIN_MENU_LIST_T {
  id: number
  theme: string
  icon: string
  menu: string[]
}

const MAIN_MENU_LIST: MAIN_MENU_LIST_T[] = [
  {
    id: 0,
    theme: '한식',
    icon: koreanIcon,
    menu: [
      '비빔밥',
      '김치찌개',
      '된장찌개',
      '불고기 덮밥',
      '제육볶음',
      '갈비탕',
      '해물파전',
      '칼국수',
      '잡채밥',
      '삼겹살',
      '냉면',
      '순두부찌개',
      '떡갈비',
      '찜닭',
      '보쌈',
      '육개장',
      '닭볶음탕',
      '낙지볶음',
      '콩나물 국밥',
      '만둣국',
    ],
  },
  {
    id: 1,
    theme: '일식',
    icon: japaneseIcon,
    menu: [
      '초밥',
      '라멘',
      '돈까스',
      '우동',
      '회',
      '규동',
      '오므라이스',
      '텐동',
      '야키소바',
      '카레라이스',
      '회덮밥',
      '샤브샤브',
      '스키야키',
      '타코야키',
      '오코노미야키',
      '도리야키',
      '오니기리',
      '냉모밀',
      '모츠나베',
      '가츠동',
    ],
  },
  {
    id: 2,
    theme: '중식',
    icon: chineseIcon,
    menu: [
      '짜장면',
      '짬뽕',
      '탕수육',
      '마파두부',
      '볶음밥',
      '울면',
      '팔보채',
      '양장피',
      '깐풍기',
      '라조기',
      '훠궈',
      '마라탕',
      '해물누룽지탕',
      '유산슬',
      '북경오리',
      '깐쇼새우',
      '크림새우',
      '짜장밥',
      '유린기',
      '해파리냉채',
    ],
  },
  {
    id: 3,
    theme: '양식',
    icon: westernIcon,
    menu: [
      '스테이크',
      '까르보나라',
      '뽀모도로',
      '알리오올리오',
      '리조또',
      '샌드위치',
      '감바스',
      '바베큐 립',
      '라자냐',
      '퀘사디아',
      '로스트 비프',
      '맥앤치즈',
      '크로켓',
      '파니니',
      '오믈렛',
      '프렌치 토스트',
      '에그베네딕트',
      '타코',
      '뇨끼',
      '스튜',
    ],
  },
  {
    id: 4,
    theme: '아시안',
    icon: asianIcon,
    menu: ['쌀국수', '팟타이', '반미', '똠양꿍', '딤섬', '사모사', '코코넛 커리', '인도 커리와 난', '사테', '짜조', '망고밥', '쏨땀', '반쎄오', '나시고랭', '미고랭'],
  },
  {
    id: 5,
    theme: '패스트푸드',
    icon: fastfoodIcon,
    menu: [
      '치즈버거',
      '새우버거',
      '불고기버거',
      '화이트갈릭버거',
      '싸이버거',
      '베이컨 토마토 디럭스 버거',
      '와퍼 주니어',
      'BLT 뉴올리언스 치킨 버거',
      '징거더블다운맥스',
      '맥스파이시 상하이버거',
      '버팔로 윙',
      '베이컨 포테이토 피자',
      '하와이안 피자',
      '고르곤 졸라 피자',
      '페퍼로니 피자',
      '콤비네이션 피자',
      '고구마피자',
      '불고기피자',
      '치킨버거',
      '빅맥',
    ],
  },
  {
    id: 6,
    theme: '치킨',
    icon: chickenIcon,
    menu: [
      '황금올리브',
      '레드콤보',
      '허니콤보',
      '후라이드 치킨',
      '숯불양념구이',
      '닭강정',
      '고추마요',
      '슈프림양념',
      '크크크치킨',
      '고추바사삭',
      '뿌링클',
      '옛날 통닭',
      '파닭',
      '블랙알리오',
      '블랙라벨',
      '당당치킨',
      '맛초킹',
      '자메이카 통다리구이',
      '볼케이노 치킨',
      '치토스 치킨',
    ],
  },
  {
    id: 7,
    theme: '분식',
    icon: bunsikIcon,
    menu: [
      '떡튀순',
      '김밥',
      '어묵꼬치',
      '라면',
      '만두',
      '호떡',
      '계란빵',
      '붕어빵',
      '핫도그',
      '마약김밥',
      '쫄면',
      '비빔국수',
      '비빔만두',
      '라볶이',
      '찐빵',
      '찹쌀도넛',
      '로제 떡볶이',
      '마라 떡볶이',
      '가래떡 떡볶이',
      '소떡소떡',
    ],
  },
  {
    id: 8,
    theme: '식단조절',
    icon: dietIcon,
    menu: [
      '닭가슴살',
      '그린 샐러드',
      '비건 샐러드',
      '리코타치즈 샐러드',
      '버섯 샐러드',
      '연어 포케',
      '우삼겹 웜볼',
      '칠리 베이컨 웜볼',
      '오트밀 죽',
      '아보카도 샐러드',
      '스무디 볼',
      'ABC 주스',
      '연어 샐러드',
      '단호박 스프',
      '샐러드 파스타',
      '두부 샐러드',
      '그릭요거트',
      '부채살 샐러드',
      '치킨 스낵랩',
    ],
  },
]
export default MAIN_MENU_LIST
